import {
  CategoryData,
  MonthlyPerformance,
  StoreRank,
  HistoricalTrend,
  SalesCategory,
} from "./types";

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  zh: {
    systemTitle: "Smart Retail",
    systemSubtitle: "连锁零售链上账本",
    nav_dashboard: "数据报表",
    nav_sales: "销售录入",
    nav_settings: "设置",
    nav_support: "帮助支持",
    search_placeholder_dashboard: "搜索数据...",
    search_placeholder_sales: "搜索交易记录...",
    filter_date: "日期范围",
    filter_country: "区域",
    all_countries: "所有区域",
    filter_country_ph: "输入区域...",
    filter_store: "店铺",
    all_stores: "所有门店",
    filter_store_ph: "输入门店...",
    btn_export_csv: "导出 CSV",
    btn_pdf_report: "导出 PDF",
    chart_pie_title: "品类销售额占比",
    chart_pie_sub: "古吉拉特店与拉哈尔店 5月16-21日 聚合占比",
    chart_bar_title: "古吉拉特店销售趋势 (日进店/成交/转化率)",
    chart_bar_sub: "每日表现统计",
    chart_donut_title: "品类销量汇总占比",
    chart_rank_title: "门店业绩排行",
    chart_line_title: "每日品类销售数量波动趋势",
    cat_phone: "智能手机",
    cat_acc: "数码配件",
    cat_large: "智能家电",
    cat_small: "冷风机与小家电",
    phone_devices: "智能手机",
    accessories: "数码配件",
    large_appliances: "智能大家电",
    small_appliances: "极客小家电",
    tag_live: "真实账本",
    unit_pcs: "台/件",
    m1: "16日",
    m2: "17日",
    m3: "18日",
    m4: "19日",
    m5: "20日",
    m6: "21日",
    m7: "均值",
    ym1: "5月16日",
    ym2: "5月17日",
    ym3: "5月18日",
    ym4: "5月19日",
    ym5: "5月20日",
    ym6: "5月21日",
    d516: "5月16日",
    d517: "5月17日",
    d518: "5月18日",
    d519: "5月19日",
    d520: "5月20日",
    d521: "5月21日",
    store_1: "古吉拉特店",
    store_2: "拉哈尔店",
    store_3: "店铺3",
    date_range_1: " (5月16-21日)",
    date_range_2: " (5月16-21日)",
    footer: "Smart Retail 真实业务账本 // 古吉拉特与拉哈尔销售网点",
    lang_toggle: "EN / 中",
    stat_up: "古吉拉特累计: $23,104",
    stat_up_acc: "累计配件销售: $1,850",
    stat_down: "拉哈尔累计: $4,935",
    stat_up_small: "累计小电销售: $1,650",
    sku_active_3: "Infinix/Tecno/三星 活跃中",
    sku_active_2: "数码配件/礼品 活跃中",
    sku_active_8: "彩电/空调/冰箱 活跃中",
    th_category: "细分类目",
    th_quantity: "销售数量",
    th_amount: "销售金额",
    btn_add_category: "添加商品",
    own_brand: "自主专营",
    other_brand: "非自主专营",
    label_internal: "特许",
    label_high_power: "高功耗",
    th_item_name: "物料名称",
    th_qty_short: "数量",
    th_amt_short: "金额",
    item_fridge: "冰箱",
    item_tv: "彩电",
    item_freezer: "冰柜",
    item_ac: "空调",
    item_washer: "洗衣机",
    item_fan: "冷风机",
    item_microwave: "微波炉",
    item_cooker: "灶具",
    verify_title: "确认每日录入",
    verify_desc: "数据将上传至连锁零售链上不可篡改的共识节点，请核实。",
    btn_submit_verify: "提交并核验",
    notif_pending: "区块广播中",
    notif_pending_desc: "正在生成加密 Hash 并向节点广播交易...",
    notif_success: "共识核验成功",
    confirmations: "次区块确认",
    explorer: "浏览器",
    btn_new_tx: "新建数据录入",
    toast_csv_exported: "CSV 报表文件已全自动生成并保存至本地。",
    toast_pdf_generating: "正在绘制高保真 PDF 报表...",
    toast_pdf_ready: "A4 PDF 报表已生成并自动下载至您的本地磁盘。",
    dialog_add_title: "录入新商品物料",
    dialog_add_name_zh: "物料中文名称",
    dialog_add_name_en: "物料英文名称",
    dialog_add_qty: "初始销售数量",
    dialog_add_price: "商品单价 ($)",
    dialog_submit: "确认录入",
    dialog_cancel: "取消",
    dialog_is_internal: "设为特许专营品牌",
    search_nodata: "未匹配到任何相关数据",
  },
  en: {
    systemTitle: "Smart Retail",
    systemSubtitle: "Consensus Ledger System",
    nav_dashboard: "Analytics",
    nav_sales: "Sales Entry",
    nav_settings: "Settings",
    nav_support: "Support",
    search_placeholder_dashboard: "Search metrics...",
    search_placeholder_sales: "Search chain ledger...",
    filter_date: "Date Range",
    filter_country: "Region",
    all_countries: "All Regions",
    filter_country_ph: "Enter region...",
    filter_store: "Store",
    all_stores: "All Stores",
    filter_store_ph: "Enter store ID...",
    btn_export_csv: "Export CSV",
    btn_pdf_report: "Export PDF",
    chart_pie_title: "Category Share by Revenue",
    chart_pie_sub: "Gujarat & Lahore Stores May 16-21 aggregated",
    chart_bar_title: "Gujarat Store Footfall & Conversion Rate",
    chart_bar_sub: "Daily Conversion Dynamics",
    chart_donut_title: "Category Share by Quantity",
    chart_rank_title: "Store Performance Ranking",
    chart_line_title: "Daily Category Unit Sales Trends",
    cat_phone: "Smartphones",
    cat_acc: "Accessories",
    cat_large: "Smart Appliances",
    cat_small: "Coolers & Small Tech",
    phone_devices: "Smartphones",
    accessories: "Accessories",
    large_appliances: "Large Appliances",
    small_appliances: "Small Appliances",
    tag_live: "LEDGER ON",
    unit_pcs: "PCS",
    m1: "16th",
    m2: "17th",
    m3: "18th",
    m4: "19th",
    m5: "20th",
    m6: "21st",
    m7: "AVG",
    ym1: "May 16",
    ym2: "May 17",
    ym3: "May 18",
    ym4: "May 19",
    ym5: "May 20",
    ym6: "May 21",
    d516: "May 16",
    d517: "May 17",
    d518: "May 18",
    d519: "May 19",
    d520: "May 20",
    d521: "May 21",
    store_1: "Gujarat Store",
    store_2: "Lahore Store",
    store_3: "Store 3",
    date_range_1: " (May 16-21)",
    date_range_2: " (May 16-21)",
    footer: "Smart Retail Real Ledger // Gujarat & Lahore Branches",
    lang_toggle: "ZH / EN",
    stat_up: "Gujarat Cum: $23,104",
    stat_up_acc: "Acc Revenue: $1,850",
    stat_down: "Lahore Cum: $4,935",
    stat_up_small: "Coolers Revenue: $1,650",
    sku_active_3: "Infinix/Tecno/Samsung Active",
    sku_active_2: "Accessories/Gifts Active",
    sku_active_8: "TV/AC/Fridge Active",
    th_category: "Category Name",
    th_quantity: "Quantity",
    th_amount: "Amount",
    btn_add_category: "Add Item",
    own_brand: "专营 Exclusive",
    other_brand: "常规 Regular",
    label_internal: "FRANCHISE",
    label_high_power: "High Power",
    th_item_name: "Material Name",
    th_qty_short: "Qty",
    th_amt_short: "Amt",
    item_fridge: "Refrigerator",
    item_tv: "Color TV",
    item_freezer: "Freezer",
    item_ac: "AC",
    item_washer: "Washer",
    item_fan: "Cooler Fan",
    item_microwave: "Microwave",
    item_cooker: "Cooker Stove",
    verify_title: "Verify Daily Entry",
    verify_desc:
      "Broadcasting records to immutable ledger consensus node. Please verify.",
    btn_submit_verify: "Submit & Verify",
    notif_pending: "Broadcasting...",
    notif_pending_desc: "Broadcasting tx and computing block hash...",
    notif_success: "Ledger Secured",
    confirmations: "Confirmations",
    explorer: "Explorer",
    btn_new_tx: "New Log Entry",
    toast_csv_exported: "CSV file compiled and downloaded successfully!",
    toast_pdf_generating: "Compiling high-fidelity A4 PDF charts...",
    toast_pdf_ready: "PDF compiled successfully and downloaded to local disk.",
    dialog_add_title: "Record New Material SKU",
    dialog_add_name_zh: "Material Name (ZH)",
    dialog_add_name_en: "Material Name (EN)",
    dialog_add_qty: "Initial Quantity",
    dialog_add_price: "Unit Price ($)",
    dialog_submit: "Record SKU",
    dialog_cancel: "Cancel",
    dialog_is_internal: "Franchise Only Brand",
    search_nodata: "No matched logs found",
  },
};

// 1. 5月16日 - 21日，古吉拉特店与拉哈尔店聚合销售占比
export const INITIAL_CATEGORY_PIE: CategoryData[] = [
  {
    id: "mobile",
    nameKey: "cat_phone",
    percentage: 83,
    value: 23258,
    qty: 109,
    color: "#3b82f6",
  }, // 智能手机
  {
    id: "large",
    nameKey: "cat_large",
    percentage: 17,
    value: 4780,
    qty: 13,
    color: "#ef4444",
  }, // 智能大家电
  {
    id: "accessories",
    nameKey: "cat_acc",
    percentage: 0,
    value: 0,
    qty: 0,
    color: "#10b981",
  }, // 配件
  {
    id: "small",
    nameKey: "cat_small",
    percentage: 0,
    value: 0,
    qty: 0,
    color: "#a855f7",
  }, // 冷风机与微波炉小电
];

// 2. 每日进店、成交、转化率表现 (以古吉拉特店数据为例，完美契合真实录入)
export const INITIAL_MONTHLY_PERFORMANCE: MonthlyPerformance[] = [
  {
    monthKey: "m1",
    data: {
      mobile: 17,
      accessories: 0,
      largeAppliances: 0,
      smallAppliances: 0,
    },
  }, // 5/16: 36进店，17成交 (成交数对齐)
  {
    monthKey: "m2",
    data: {
      mobile: 12,
      accessories: 0,
      largeAppliances: 2,
      smallAppliances: 0,
    },
  }, // 5/17: 32进店，14成交
  {
    monthKey: "m3",
    data: {
      mobile: 19,
      accessories: 0,
      largeAppliances: 0,
      smallAppliances: 0,
    },
  }, // 5/18: 34进店，19成交
  {
    monthKey: "m4",
    data: {
      mobile: 12,
      accessories: 0,
      largeAppliances: 2,
      smallAppliances: 0,
    },
  }, // 5/19: 44进店，14成交
  {
    monthKey: "m5",
    data: {
      mobile: 13,
      accessories: 0,
      largeAppliances: 2,
      smallAppliances: 0,
    },
  }, // 5/20: 29进店，15成交
  {
    monthKey: "m6",
    data: {
      mobile: 15,
      accessories: 0,
      largeAppliances: 4,
      smallAppliances: 0,
    },
  }, // 5/21: 43进店，19成交
];

export const INITIAL_STORE_RANKING: StoreRank[] = [
  {
    rank: 1,
    storeKey: "store_1",
    sales: 23104,
    dateKey: "date_range_1",
    percentage: 82,
  }, // 古吉拉特店
  {
    rank: 2,
    storeKey: "store_2",
    sales: 4935,
    dateKey: "date_range_2",
    percentage: 18,
  }, // 拉哈尔店
  {
    rank: 3,
    storeKey: "store_3",
    sales: 0,
    dateKey: "date_range_1",
    percentage: 0,
  }, // 店铺3
];

// 4. 每日两店销量加总合并波动趋势
export const INITIAL_HISTORICAL_TRENDS: HistoricalTrend[] = [
  {
    ymKey: "d516",
    mobile: 22,
    accessories: 0,
    largeAppliances: 0,
    smallAppliances: 0,
  }, // 5/16加总
  {
    ymKey: "d517",
    mobile: 12,
    accessories: 0,
    largeAppliances: 2,
    smallAppliances: 0,
  }, // 5/17加总
  {
    ymKey: "d518",
    mobile: 25,
    accessories: 0,
    largeAppliances: 0,
    smallAppliances: 0,
  }, // 5/18加总
  {
    ymKey: "d519",
    mobile: 18,
    accessories: 0,
    largeAppliances: 2,
    smallAppliances: 0,
  }, // 5/19加总
  {
    ymKey: "d520",
    mobile: 15,
    accessories: 0,
    largeAppliances: 2,
    smallAppliances: 0,
  }, // 5/20加总
  {
    ymKey: "d521",
    mobile: 17,
    accessories: 0,
    largeAppliances: 7,
    smallAppliances: 0,
  }, // 5/21加总
];

// 5. 销售录入商品预设明细清单 (以 5月21日 销售录入的实际商品进行对齐)
export const INITIAL_SALES_CATEGORIES: SalesCategory[] = [
  {
    id: "mobile",
    nameKey: "phone_devices",
    items: [
      {
        id: "m-tecno",
        nameZh: "TECNO",
        nameEn: "TECNO",
        quantity: 6,
        unitPrice: 150.0,
      },
      {
        id: "m-infinix",
        nameZh: "Infinix",
        nameEn: "Infinix",
        quantity: 6,
        unitPrice: 177.0,
      },
      {
        id: "m-itel",
        nameZh: "ITEL",
        nameEn: "ITEL",
        quantity: 5,
        unitPrice: 127.8,
      },
    ],
  },
  {
    id: "accessories",
    nameKey: "accessories",
    items: [
      {
        id: "a-own",
        nameZh: "自有品牌",
        nameEn: "Own Brand",
        quantity: 0,
        unitPrice: 15.0,
        isInternal: true,
      },
      {
        id: "a-other",
        nameZh: "非自有品牌",
        nameEn: "Other Brand",
        quantity: 0,
        unitPrice: 8.0,
      },
    ],
  },
  {
    id: "large",
    nameKey: "large_appliances",
    items: [
      {
        id: "l-fridge",
        nameZh: "冰箱",
        nameEn: "Refrigerator",
        quantity: 1,
        unitPrice: 322.5,
      },
      {
        id: "l-tv",
        nameZh: "电视",
        nameEn: "TV",
        quantity: 2,
        unitPrice: 310.0,
      },
      {
        id: "l-freezer",
        nameZh: "冰柜",
        nameEn: "Freezer",
        quantity: 2,
        unitPrice: 180.0,
      },
      {
        id: "l-ac",
        nameZh: "空调",
        nameEn: "AC",
        quantity: 0,
        unitPrice: 250.0,
      },
      {
        id: "l-washer",
        nameZh: "洗衣机",
        nameEn: "Washer",
        quantity: 0,
        unitPrice: 240.0,
      },
      {
        id: "l-fan",
        nameZh: "风扇",
        nameEn: "Fan",
        quantity: 0,
        unitPrice: 50.0,
      },
      {
        id: "l-microwave",
        nameZh: "微波炉",
        nameEn: "Microwave Oven",
        quantity: 2,
        unitPrice: 113.0,
      },
      {
        id: "l-cooker",
        nameZh: "灶具",
        nameEn: "Cooker",
        quantity: 0,
        unitPrice: 150.0,
      },
    ],
  },
  {
    id: "small",
    nameKey: "small_appliances",
    items: [
      {
        id: "s-own",
        nameZh: "自有品牌",
        nameEn: "Own Brand",
        quantity: 0,
        unitPrice: 120.0,
        isInternal: true,
      },
      {
        id: "s-other",
        nameZh: "非自有品牌",
        nameEn: "Other Brand",
        quantity: 0,
        unitPrice: 80.0,
      },
    ],
  },
];
